#!/usr/bin/python

import sys
import math
from ROOT import *

def cMuonDIS(canvas):
  c = TCanvas('cMuonDIS','cMuonDIS',1200,400)
  canvas.Add(c)
  c.Divide(3)
  pad1 = c.cd(1)
  pad1.SetLogy()
  pad1.SetLogx()
  pad1.SetLeftMargin(0.2)
  pad1.SetRightMargin(0.02)
  h = gROOT.FindObject('hMuonPt_DIS')
  h.SetStats(0)
  h.SetMinimum(0.9)
  h.SetLineColor(3)
  h.DrawCopy()
  hM = gROOT.FindObject('hMuonPt_MEN')
  hM.SetMinimum(0.9)
  hM.SetLineColor(4)
  hM.GetXaxis().SetRange(3,38)
  hM.GetXaxis().SetTitleOffset(1.4)
#  hM.DrawCopy('same')
  hM.DrawCopy()
  pad2 = c.cd(2)
  pad2.SetLeftMargin(0.2)
  pad2.SetRightMargin(0.01)
  h = gROOT.FindObject('hMuonEta_DIS')
  h.GetYaxis().SetTitleOffset(1.8)
  h.SetMinimum(0.)
  h.SetStats(0)
  h.SetLineColor(4)
  h.DrawCopy()
  hM = gROOT.FindObject('hMuonEta_MEN')
  hM.SetMinimum(0)
  hM.SetLineColor(4)
#  hM.DrawCopy('same')
  hM.DrawCopy()
  pad3 = c.cd(3)
  pad3.SetLeftMargin(0.2)
  pad3.SetRightMargin(0.01)
  h = gROOT.FindObject('hMuonPhi_DIS')
  h.SetMinimum(0.)
  h.SetLineColor(3)
  h.SetStats(0)
  h.DrawCopy()
  hM = gROOT.FindObject('hMuonPhi_MEN')
  hM.SetStats(0)
  hM.SetMinimum(0.)
  hM.SetLineColor(4)
# hM.DrawCopy('same')
  hM.DrawCopy()
  c.Update()
  return
def cMuonPtVsEta(canvas):
  c = TCanvas('cMuonPtVsEta','cMuonPtVsEta',1200,600)
  canvas.Add(c)
  c.Divide(3)
  pad1 = c.cd(1)
  h = gROOT.FindObject('hMuonPtVsEta_Gl')
  h.SetStats(0)
  h.SetMinimum(0.)
  h.DrawCopy("box")
  pad2 = c.cd(2)
  h = gROOT.FindObject('hMuonPtVsEta_Ma')
  h.SetMinimum(0.)
  h.SetStats(0)
  h.DrawCopy("box")
  pad3 = c.cd(3)
  h = gROOT.FindObject('hMuonPtVsEta_Tk')
  h.SetMinimum(0.)
  h.SetStats(0)
  h.DrawCopy("box")
  c.Update()
  return

def plotAll(canvas) :
  cMuonDIS(canvas)
# cMuonPtVsEta(canvas)
  return

